### ISSUE TITLE
Error when deleting a parent node bug

### ISSUE THREAD

**Issue by jplevene** [vakata/jstree#2611]
Since updating to 3.3.12, a few users have been reporting that sometimes when deleting a parent node it does not delete.  I managed to get a console error after executing the following commands

```
var nodes = $("#tree").jstree("get_top_selected", true);
$("#tree").jstree("delete_node", nodes); 
```

The console error reads:
![Screenshot 2022-02-22 130007](https://user-images.githubusercontent.com/1764110/155335447-ae242cd5-fddc-4583-a694-c5bf49d8579c.png)

This does not happen all the time, thus it took me ages to finally get a console image from a customer.

**Comment by kedniko** [comment]
Error:  `Uncaught TypeError: this.get_node(...).children(...).triger is not a function`
Problem: There is a typo in the library.
Solution: Just search and replace `triger` with` trigger`

**Comment by jplevene** [comment]
I already reported it as issue 2614 (https://github.com/vakata/jstree/issues/2614)
